@baseUrl = http://localhost:53625

### Register a new customer

POST {{baseUrl}}/api/customers HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "gender": "male",
  "email": "john_doe@gmail.com",
  "dateOfBirth": "1990-01-01"
}

### Gets a list of all customers

GET {{baseUrl}}/api/customers HTTP/1.1
accept: application/json