### 
# @name createCustomers
POST http://localhost:5072/api/customers HTTP/1.1
accept: application/json
accept-encoding: gzip, deflate, br
content-type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "gender": "male",
  "email": "john_doe@gmail.com",
  "dateOfBirth": "1990-01-01"
}

### 
# @name getCustomers
GET http://localhost:5072/api/customers HTTP/1.1
accept: application/json