@baseUrl = http://localhost:5072/api

### Cadastrar um novo cliente
# @name createCustomer
POST {{baseUrl}}/customers HTTP/1.1
content-type: application/json

{
  "firstName": "Jean",
  "lastName": "Gatto",
  "gender": "Male",
  "email": "jean_gatto@hotmail.com",
  "dateOfBirth": "1990-04-27"
}

@customerId = {{createCustomer.response.body.result.id}}

### Obter cliente por id
# @name getCustomersById
GET {{baseUrl}}/customers/{{customerId}} HTTP/1.1
content-type: application/json

### Obter todos os clientes
# @name getCustomers
GET {{baseUrl}}/customers HTTP/1.1
content-type: application/json