using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shop.Core.SharedKernel;

namespace Shop.Infrastructure.Data.Extensions;

internal static class EntityTypeBuilderExtensions
{
    extension<TEntity>(EntityTypeBuilder<TEntity> builder) where TEntity : BaseEntity
    {
        /// <summary>
        /// Configures the base entity for a given entity type.
        /// </summary>
        public void ConfigureBaseEntity()
        {
            // Sets the primary key for the entity to the Id property.
            builder
                .HasKey(entity => entity.Id);

            // Configures the Id property to be required (NOT NULL) and not generated by the database.
            builder
                .Property(entity => entity.Id)
                .IsRequired()
                .ValueGeneratedNever();

            // Ignores the DomainEvents property for the entity.
            builder
                .Ignore(entity => entity.DomainEvents);
        }
    }

}