# https://github.com/actions/setup-dotnet
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6.0.0
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore Shop.slnx

      - name: Build
        run: dotnet build Shop.slnx --nologo --no-restore --configuration Release

      - name: Test
        run: dotnet test Shop.slnx --nologo --no-build --no-restore --configuration Release --verbosity minimal
